---
- name: Install Apache Tomcat
  hosts: all
  become: true

  tasks:
  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Install Java
    apt:
      name: openjdk-8-jdk
      state: present

  - name: Download Apache Tomcat
    get_url:
      url: "https://downloads.apache.org/tomcat/tomcat-9/v9.0.55/bin/apache-tomcat-9.0.55.tar.gz"
      dest: /tmp/apache-tomcat-9.0.55.tar.gz
